listener {
    timeout = 650
    on-timeout = systemctl suspend
    on-resume = notify-send "you have resumed"
}

listener {
    timeout = 620
    on-timeout = exec "xset dpms force off"
    on-resume = exec "xset dpms force on"  # ✅ Corrected
}


listener {
    timeout = 500  # Lock after 10 seconds
    on-timeout = exec "hyprlock"
}











